from .exceptions import APIError as APIError
from .tank import AsyncTank as AsyncTank, Tank as Tank
from _typeshed import Incomplete

DEFAULT_SERVER: str
WSDL_PATH: str
WSDL_URL: Incomplete

class SensorClient:
    def __init__(self) -> None: ...
    def login(self, username, password) -> None: ...
    @property
    def tanks(self): ...

class AsyncSensorClient:
    def __init__(self, base=...) -> None: ...
    async def __aenter__(self): ...
    async def __aexit__(self, exc_t, exc_v, exc_tb) -> None: ...
    async def login(self, username, password): ...
    async def tanks(self): ...
