class Tank:
    def __init__(self, soap_client: object, signalman_no: str) -> None: ...
    @property
    def level(self) -> int: ...
    @property
    def serial_number(self) -> str: ...
    @property
    def model(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def capacity(self) -> int: ...
    @property
    def last_read(self) -> str: ...
    @property
    def history(self): ...

class AsyncTank:
    def __init__(self, soap_client: object, signalman_no: str) -> None: ...
    async def level(self) -> int: ...
    async def serial_number(self) -> str: ...
    async def model(self) -> str: ...
    async def name(self) -> str: ...
    async def capacity(self) -> int: ...
    async def last_read(self) -> str: ...
    async def history(self): ...

def unpack_tank_data(cls, response) -> None: ...
def transform_history_data(data): ...
